// OTP helpers shared by generate* and verify* callables.
//
// Storage scheme (locked decision, see memory-bank/decisions.md):
//   - 6-digit code, generated by crypto.randomInt
//   - Per-task random salt (16 bytes hex)
//   - SHA-256 hash of `${code}:${salt}` stored on task doc
//   - 10-minute TTL via Timestamp on task doc
//   - Plaintext returned ONCE to the customer in the generate callable
//     response; never written to Firestore in plaintext; never sent to
//     the volunteer's client; never logged.

import { createHash, randomBytes, randomInt } from 'crypto';

export const OTP_TTL_MS = 10 * 60 * 1000;

export function generateOtpCode(): string {
  return randomInt(0, 1_000_000).toString().padStart(6, '0');
}

export function generateSalt(): string {
  return randomBytes(16).toString('hex');
}

export function hashOtp(code: string, salt: string): string {
  return createHash('sha256').update(`${code}:${salt}`).digest('hex');
}

export function constantTimeEquals(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}
